CREATE TABLE clinical_info(patient_id INT NOT NULL PRIMARY KEY,
final_grade INT,
dcis_seen INT,
lvi_seen INT,
ln_status INT,
age_at_diagnosis NUMERIC,
tumour_size_categorical INT,
involved_ln_total_dec NUMERIC,
involved_ln_low_dec NUMERIC,
involved_ln_mid_dec NUMERIC,
involved_ln_high_dec NUMERIC,
extra_nodal_spread INT,
t_dmfs NUMERIC (3,2),
e_dmfs INT,
last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP)