CREATE TABLE ln_histological_info(patient_ id INT NOT NULL PRIMARY KEY,
gc_location INT,
gc_size INT,
large_gc INT,
Semi_quantitative_assessment_gc_number INT,
gc_present INT,
sinus_histocitosis INT,
gc_location_mets INT,
gc_size_mets INT,
large_gc_mets INT,
Semi_quantitative_assessment_gc_mets INT,
gc_present_mets INT,
sinus_histocitosis_mets INT,
mets_pattern INT,
last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP)